### ISSUE TITLE
스터디 진행을 위해 할 일

### ISSUE THREAD

**Issue by yuhodots** [cse-study/cse-study.github.io#1]
1. 스터디 목표 / 설명글

 - 지금 생각: 강제로 AI 테크 소식 기록. 최신 기술 블로그 글 / 유튜브 영상 / 등 아무거나 자신이 관심이 있는 것을 보고 링크 공유 & 세줄 요약 + 느낀점,소감, 한줄평 (매주 1회, 올해 인당 40개 정도 쌓이는 것 목표)
 - 영양가 없어도 됨 그냥 보는거 자체가 목표
 - 해당 내용들 블로그 about에 기록하기
 - 공부한 자료를 링크만 걸어서 세줄 요약 할 것이긴 하지만, 혹시나 저작권 관련 문제 없는지 찾아보기

2. 블로그 형식으로 만들기

- 세줄 요약에 최적화된 템플릿으로
- https://github.com/wayjam/hugo-theme-fluency
- https://github.com/cntrump/hugo-notepadium
- https://quizzical-clarke-e80392.netlify.app/ 이런것 처럼 popup, modal 이어도 좋을듯
- https://papers.labml.ai/papers/daily/
- 자동화 적용해서 매주 한번씩 자동으로 repository 내용 배포하도록 설정

3. 최신 AI 자료 얻을 수 있는 링크들 스크랩해서 정리하기

- https://papers.labml.ai/papers/daily/
- https://www.youtube.com/c/YannicKilcher/videos
- http://www.arxiv-sanity.com/
- https://www.reddit.com/r/MachineLearning/
- https://paperswithcode.com/newsletter
- 등등...

4. 더 추가할 사항 고민

**Comment by yuhodots** [comment]
블로그 메뉴는 크게 3개로 나누기

1. 메인페이지: 3줄요약 포스팅 나열
2. Help 페이지: 블로그 글 작성 방법 / ai 기술 블로그 링크 리스트 / 스터디 규칙 적어두기
3. About 페이지: 참여자 / 기간 / 스터디 목표 등에 대한 간단한 소개

**Comment by yuhodots** [comment]
알고리즘/코테 준비 카테고리도 고려하고 있기

**Comment by yuhodots** [comment]
참여 인원들이 이후에 취업/진로에도 최대한 활용할 수 있도록 블로그 구성하기

**Comment by bwmelon97** [comment]
스터디, 블로그 포스팅의 범위(주제)도 논의가 이루어지면 좋을 것 같습니다.

1. 알고리즘 / 코테
2. AI / 최근 기술 동향
3. CS / 전공 지식
...

CS 분야를 추가한 것은 대기업, 대기업이 인수한 스타트업, 개발자 규모가 어느 정도 구축된 스타트업 등의 기술 면접에서 CS 관련 질문을 하는 경우가 많기 때문입니다.
(+ 개인적으로 아직 학부 졸업을 못한 상태라, 학과 공부에 도움이 되는 이유도 있습니다 😅)

다만 만약 스터디 인원과 함께 카테고리도 계속해서 늘어나게 된다면, 각자 원하는 스터디 주제만을 포스팅하는 방식으로 블로그가 중구난방이 될 수도 있고, 스터디의 방향성을 잃게 될 수도 있다고 생각합니다.

---

따라서, 스터디 인원의 공동 목표를 정한 이후에, 포스팅 카테고리를 명확하게 정하는 시간을 가지면 좋겠습니다 !
(만약 블로그에 올릴 카테고리가 너무 많아지게 된다면, 동일한 탬플릿의 블로그를 추가 개설해서 구분하는 것도 방법이 될 수도 있을 것 같습니다.)

**Comment by yuhodots** [comment]
@bwmelon97 

좋습니다!!

---

사실 지운이랑 나랑 둘이 **ai 관련 매주 최신 동향 살피고 세줄 요약하는 스터디(?)도 따로 진행**하기로 해서

지금 위에 적어둔거는 '알고리즘/코테 스터디'는 아니고 'ai 관련 스터디'에 대해서 적어놓았습니다! 

근데 말씀하신 것 처럼 카테고리 명확하게 정하는 시간 가지면 좋을 것 같고

아니면 아예 organization 그룹을 파서, 레포를 각각 나눠도 좋을 것 같습니다!!

---

ai 관련 스터디도 참여 의향이 있다면 ㅎㅎ... 언제든.. 환영 ^-^

**Comment by bwmelon97** [comment]
@yuhodots 
Organization 만드는거 아주 좋은 의견이군요 !
스터디할 생각에 벌써부터 두근두근합니다 😆

**Comment by yuhodots** [comment]
blog 레포로 내용을 옮겨 이슈를 닫습니다.
