### ISSUE TITLE
재미있게 공부하기 위해서

### ISSUE THREAD

**Issue by yuhodots** [cse-study/cse-study.github.io#2]
머리도 식힐 겸 시간날 때 마다 블로그에 이스터에그 같은 요소도 넣고 싶음.. (희망사항임)

- 너무 복잡하면, 그냥 의지를 잃지 말자고 명언집이나 하나 만들어서 명언 수집이나 해야겠다 ㅎ.ㅎ

**Comment by bwmelon97** [comment]
![image](https://user-images.githubusercontent.com/39655003/150078997-07dac2de-eabd-42da-b7d3-c4be89701c6c.png)

**Comment by yuhodots** [comment]
이슈 컽!
